site_name: Saposs Documentation
theme:
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
nav:
  - 'Welcome to Saposs': 'index.md'
  - 'Introduce Saposs WF': 'intro-saposs-wf.md'
  - 'Introduce Saposs Aquarium': 'intro-saposs-aquarium.md'
  - 'Quick Tour': 'quick-tour.md'
  - 'What is Saposs Component?': 'what-is-saposs-component.md'
  - 'Create a new View': 'create-a-view.md'
  - 'Create a new Handler': 'create-a-handler.md'
  - 'Create a new Service': 'create-a-service.md'
  - 'Connect View-Handler-Service': 'connect-view-handler-service.md'
  - 'Upload Component': 'upload-component-saposs-wf.md'
  - 'Synchronize Online Components': 'sync-online-component.md'
  - 'Manage Live Projects': 'manage-live-projects.md'
  - 'Hello World Desktop Tutorial': 'hello-world-wf-tutorial.md'
  - 'Hello World Web Tutorial': 'hello-world-aquarium-tutorial.md'
  - 'About Documentation': 'about.md'
markdown_extensions:
  - codehilite
site_description: 'All documents and user guides for Saposs.'
site_author: 'saposs'
repo_url: https://github.com/saposs-org
google_analytics: ['UA-89360024-2', 'saposs.com']
copyright: 'Copyright 2019 by <a href="http://www.saposs.com">Saposs</a>. All rights reserved.'
extra:
  feature:
    tabs: false
  social:
    - type: globe
      link: http://www.saposs.com
    - type: github-alt
      link: https://www.github.com/saposs-org
    - type: twitter
      link: https://www.twitter.com/the_saposs
    - type: facebook
      link: https://www.facebook.com/the.saposs